### ISSUE TITLE
The calculation of log_q in bgcn.py

### ISSUE THREAD

**Issue by MatoCom** [stadlmax/Graph-Posterior-Network#1]
Hi,
In gpn/models/bgcn.py line 110,
I think there is a small mistake.
Shouldn't it be like `self.conv_1.log_q + self.conv_2.log_q`?
Thanks for reading.

**Comment by MatoCom** [comment]
Also, there seems to be a typing mistake at gpn/nn/transductive_graph_engine.py line 209
`results[s] = {**results[s], **ood_results[s]}`

**Comment by stadlmax** [comment]
Hi, 
thank you for spotting those typos.
