### ISSUE TITLE
ResolvePackageNotFound for installing the conda environment

### ISSUE THREAD

**Issue by vietngth** [stadlmax/Graph-Posterior-Network#2]
Hi, I tried to install the conda environment for the repo and encountered this problem:

```
(base) viet@cad660901:~/work/Graph-Posterior-Network$ conda env create -f gpn_environment.yml python==3.8 --force
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - python==3.8.3=hcff3b4d_2c
```

I wonder if there is any change from your side that I should follow? Thank you.

**Comment by xyang2316** [comment]
> Hi, I tried to install the conda environment for the repo and encountered this problem:
> 
> ```
> (base) viet@cad660901:~/work/Graph-Posterior-Network$ conda env create -f gpn_environment.yml python==3.8 --force
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - python==3.8.3=hcff3b4d_2c
> ```
> 
> I wonder if there is any change from your side that I should follow? Thank you.

Met the same problem. Any suggestions would be helpful, thank you!

**Comment by mtntruong** [comment]
There might be some changes in Anaconda's repositories. Edit line 123 of `gpn_environment.yml` as follows  
Old
```
  - python=3.8.3=hcff3b4d_2c
```
New
```
  - python=3.8.3=hcff3b4d_2
```
And you're good to go.

**Comment by stadlmax** [comment]
You probably are right. There were no changes on our side.

**Comment by stadlmax** [comment]
If someone could confirm that this simple change of the pinned version leads to a working solution, I can close this issue.

**Comment by xyang2316** [comment]
> If someone could confirm that this simple change of the pinned version leads to a working solution, I can close this issue.

It works on my side, I can create the gpn conda environment after doing the modification. Thank you for your help!

**Comment by vietngth** [comment]
Confirm working on my side as well. Thank you!
